version: 2
updates:
  - package-ecosystem: gomod
    directory: /apps/api-go
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /apps/worker-go
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/api-go
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/worker-go
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
